### ISSUE TITLE
Newlines not handled properly

### ISSUE THREAD

**Issue by bbirand** [FormidableLabs/css-to-radium#3]
Hi,

When there are newlines in the original CSS, they are not properly escaped in the produced Javascript. For instance, this snippet:

``` css
article,
aside,
details,
figcaption,
figure,
footer,
header,
hgroup,
main,
menu,
nav,
section,
summary {
  display: block;
}
```

becomes

``` javascript
  'article,
aside,
details,
figcaption,
figure,
footer,
header,
hgroup,
main,
menu,
nav,
section,
summary': {
    display: 'block'
  }
```
